export default function CollectionHeroOverlay() {
    return (
        <>
            <div
                aria-hidden
                className="
                    pointer-events-none
                    absolute
                    inset-0
                    z-10
                    bg-gradient-to-b
                    from-black/35
                    via-transparent
                    to-black/55
                "
            />
            <div
                aria-hidden
                className="
                    pointer-events-none
                    absolute
                    inset-0
                    z-10
                    bg-gradient-to-r
                    from-black/30
                    via-transparent
                    to-black/30
                "
            />
        </>
    );
}